name: main

permissions:
  issues: write
  actions: write
  contents: write

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Publish test data workflow dispatch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "publish_test_data.yml",
              ref: "main",
              inputs: {
                name: "dev",
                datacenter: "AWS"
              },
            })

      - name: Get workflow ID's
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "publish_test_data.yml",
            })  
      
      