name: main

permissions:
  issues: write
  actions: write
  contents: write

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Dispatch and Wait Workflow
        id: dispatch-and-wait
        uses: actions/github-script@v7
        with:
          script: |
            const dispatchAndWait = require('./dispatchAndWait.js');

            // Step 1: List workflow runs and save run IDs
            const initialRunIds = await dispatchAndWait.listWorkflowRuns(github, context);
            console.log(`Initial Run IDs: ${initialRunIds}`);

            // Step 2: Create workflow dispatch and get the workflow ID
            const workflowId = await dispatchAndWait.createWorkflowDispatch(github, context);
            console.log(`Dispatched workflow with ID: ${workflowId}`);

            // Step 3: Wait for a new job to be created
            const newRunIds = await dispatchAndWait.waitAndCheckNewJob(github, context, initialRunIds);
            console.log(`New Run IDs: ${newRunIds}`);

            // Step 4: Wait for the new job status to be completed
            await dispatchAndWait.waitForCompletion(github, context, newRunIds[0]);
