name: main

permissions:
  issues: write
  actions: write
  contents: write

on:
  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Publish test data workflow dispatch
        uses: aurelien-baudet/workflow-dispatch@v2
        env:
          GITHUB-TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          workflow: publist_test_data.yml
          token: env.GITHUB_TOKEN
          wait-for-completion: true
      
      