name: Publish Test Data

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Select environment
        options:
          - dev
          - test
          - qa
      datacenter:
        type: choice
        description: Select datacenter
        options:
          - AWS

jobs:
  post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install required packages
        run: |
          pip install pandas requests openpyxl

      - name: Read Excel sheet and perform POST request
        run: |
          python3 ./.github/scripts/publish_test_data.py
